# Generated by Django 4.1.5 on 2023-01-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_alter_personaldata_options_personaldata_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.PositiveIntegerField(unique=True)),
                ('personal_data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='examples.personaldata')),
            ],
            options={
                'verbose_name': 'Studenci',
            },
        ),
    ]
