# Generated by Django 4.1.5 on 2023-01-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_programme_alter_student_options_student_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examples.programme'),
        ),
    ]
