# Generated by Django 4.1.5 on 2023-01-22 12:35

from django.db import migrations, models
import django.db.models.deletion
import examples.models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0005_alter_student_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('alpha2', models.SlugField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Język',
                'verbose_name_plural': 'Języki',
            },
        ),
        migrations.AlterModelOptions(
            name='personaldata',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='first_name',
            field=models.CharField(help_text='Podaj imię - zawsze od dużej litery', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='examples.personaldata', validators=[examples.models.test_validator], verbose_name='Osoba'),
        ),
        migrations.AlterField(
            model_name='student',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examples.programme', verbose_name='Kierunek'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='languages',
            field=models.ManyToManyField(to='examples.language'),
        ),
    ]
