# Generated by Django 4.1.5 on 2023-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0006_language_alter_personaldata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
