# Generated by Django 4.1.5 on 2023-01-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_creation_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('a', 'Nieopublikowana'), ('b', 'Opublikowana')], default='a', max_length=1),
        ),
    ]
