# Generated by Django 4.1.5 on 2023-01-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
            options={
                'verbose_name': 'Lista TODO',
                'verbose_name_plural': 'Listy TODO',
                'unique_together': {('note', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ToDoListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'Aktualne'), ('b', 'Wykonane')], max_length=1)),
                ('note', models.CharField(max_length=200)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.todolist')),
            ],
            options={
                'verbose_name': 'Element listy',
                'verbose_name_plural': 'Elemnty listy',
            },
        ),
    ]
