# Generated by Django 4.1.5 on 2023-01-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_todolist_options_alter_todolistitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.profile'),
            preserve_default=False,
        ),
    ]
